### ISSUE TITLE
Port is not being used.

### ISSUE THREAD

**Issue by problematiq** [jagter/python-netbox#19] opened 2019-07-26 20:07 UTC
Can't get port to work correctly.
```
netbox = NetBox(
            use_ssl=True,
            host='*********',
            auth_token='************',
            port=8443
        )
host_info = netbox.dcim.get_devices()
```
`requests.exceptions.ConnectionError: HTTPSConnectionPool(host=********', port=443)`

**Comment by jagter** [comment] 2019-07-29 18:07
Hi,

Thank you for the bug report.
I'll let you when the bug is fixed.

**Comment by jagter** [comment] 2019-07-30 18:17
The issue is fixed in the master branch.

**Closed by jagter** 2019-07-30 18:17 UTC
